name: Create PR from Develop to Main

on:
  push:
    branches:
      - next-no-typescript  # Trigger this action on changes to develop branch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create pull request to main
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: main  # Target branch for the PR
        head: next-no-typescript  # Source branch for the PR
        title: 'Auto-merge from develop to main'
        body: 'This is an automated PR created after merging into develop.'
        branch: 'auto-merge/develop-to-main'  # Temporary branch name
        labels: 'automated-pr'
